apps/autorizacoes/urls.py
from django.urls import path
from .views import (
    AutorizadorView,
    EventoDelete,
    EventoCreate,
    EventoUnidadeList,
    EventoEdit,
    EventoView,
    AutorizacaoEventoList,
    AutorizacaoSuccess,
    AutorizacaoScheduled,
    AutorizacaoView,
    AutorizacaoCreate,
    AutorizacaoReleaseSuccess,
    AutorizacaoReleased,
    PrintAutReportView,
    EventoTipoAutorizacaoDelete,
    EventoCancel,
    AutorizacaoGerar,
    MensagensList,
    AnexaDocAutorizacao,
    RegistrarSolicitacao
)


urlpatterns = [
    path('<int:id_autorizador>/', AutorizadorView.as_view(), name='autorizador-detail'),
    path('autorizacoes/gerar/<int:pk>', AutorizacaoGerar.as_view(), name='autorizacao-gerar'),
    path('autorizacoes/create/<int:pk>', AutorizacaoCreate.as_view(), name='autorizacao-create'),
    path('evento/delete/<int:pk>/', EventoDelete.as_view(), name='evento-delete'),
    path('evento/create/', EventoCreate.as_view(), name='evento-create'),
    path('evento/list/', EventoUnidadeList.as_view(), name='evento-list'),
    path('evento/update/<int:pk>/', EventoEdit.as_view(), name='evento-update'),
    path('evento/cancel/<int:pk>/', EventoCancel.as_view(), name='evento-cancel'),
    path('evento/<int:pk>/', EventoView.as_view(), name='evento-detail'),
    path('autorizacao/list/<int:evento_id>', AutorizacaoEventoList.as_view(), name='autorizacao-list'),
    path('autorizacao/success/', AutorizacaoSuccess.as_view(), name='evento-autorizacoes-success'),
    path('autorizacao/scheduled/', AutorizacaoScheduled.as_view(), name='evento-autorizacoes-scheduled'),
    path('autorizacao/<int:pk>/', AutorizacaoView.as_view(), name='autorizacao-detail'),
    path('autorizacao/registrar/<int:pk>/', RegistrarSolicitacao.as_view(), name='solicitacao-registrar'),
    path('autorizacao/released/success/', AutorizacaoReleaseSuccess.as_view(), name='autorizacao-released-success'),
    path('autorizacao/released/', AutorizacaoReleased.as_view(), name='autorizacao-released'),
    path('autorizacao/anexar/<int:pk>', AnexaDocAutorizacao.as_view(), name='autorizacao-attach'),
    path('autorizacao/print/<int:rpt_type>/<int:evento_id>/', PrintAutReportView.as_view(), name='autorizacao-print'),
    path('evento/tipo_aut/delete/<int:pk>/', EventoTipoAutorizacaoDelete.as_view(), name='evento-ta-delete'),
    path('mensagens/list/', MensagensList.as_view(), name='mensagem-list')
]

nd_box/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', include('apps.core.urls')),
    path('manager/', admin.site.urls),
    path('carreiras/', include('apps.carreiras.urls')),
    path('reports/', include('apps.reports.urls')),
    path('privacidade/', include('apps.privacidade.urls')),
    path('autorizacoes/', include('apps.autorizacoes.urls')),
    path('healt/', include('apps.healt.urls')),
    path('jund/', include('apps.jund.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Gestão ND Box'
admin.site.site_title = 'Gestão ND Box'
admin.site.index_title = 'Área Administrativa'

apps/autorizacoes/models.py
from django.db import models
import uuid
from django.urls import reverse
from datetime import date, timedelta
from hermes import (
    send_cancel_mail,
    send_new_notification_mail
)
from apps.core.models import (
    Base,
    Turma,
    Ciclo,
    Curso,
    Unidade
)
from apps.agamotto.models import ScheduledTask
from django.utils import timezone
from django.contrib.auth.models import User


def get_file_path(_instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return filename


class Autorizador(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    user = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.PROTECT, blank=False, null=False)
    gv_code = models.IntegerField('GV Code', blank=False, null=False, unique=True)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    def send_login_mail(self):
        return self.user.name

    @property
    def name(self):
        return self.user.get_full_name()

    @property
    def email(self):
        return self.user.email

    @property
    def last_login(self):
        return self.user.last_login

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    class Meta:
        verbose_name = 'Autorizador'
        verbose_name_plural = 'Autorizadores'


class Coordenador(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    unidade = models.ForeignKey(Unidade, verbose_name='Unidade', on_delete=models.PROTECT, blank=False,
                                null=False)
    user = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.PROTECT, blank=False, null=False)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    @property
    def name(self):
        return self.user.get_full_name()

    @property
    def email(self):
        return self.user.email

    @property
    def last_login(self):
        return self.user.last_login

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    class Meta:
        verbose_name = 'Coordenador'
        verbose_name_plural = 'Coordenadores'


class Aluno(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    nome = models.CharField("Nome", max_length=100, blank=False, null=False)
    matricula = models.IntegerField("Matrícula", blank=False, null=False, unique=True)
    gv_code = models.IntegerField('GV Code', blank=False, null=False, unique=True)
    unidade = models.ForeignKey(Unidade, verbose_name='Unidade', on_delete=models.PROTECT, blank=False,
                                null=False)
    responsavel = models.ForeignKey(Autorizador, verbose_name='Autorizador', on_delete=models.PROTECT, blank=False,
                                    null=False)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    def update_enturmacao(self, gv_origin):
        self.remove_enturmacao()
        self.create_enturmacao(Turma.objects.get(gv_code=gv_origin))
        print('alteração de turma concluída!')
        # gerenciar autorizações
        aut = self.autorizacao_set.filter(ativo=True, cancelado=False)
        autorizacoes = []
        for i in aut:
            if not i.evento.is_past_due:
                autorizacoes.append(i)

        if autorizacoes:  # há autorizações para eventos futuros
            for i in autorizacoes:
                if i.evento.turma is not None:
                    i.cancelar('Aluno trocou de turma.')
        # Verificar eventos da nova turma
        eventos = Evento.objects.filter(ativo=True)
        aut = self.autorizacao_set.filter(ativo=True, cancelado=False)
        eventos_aluno = []
        for i in aut:
            eventos_aluno.append(i.evento)

        for e in eventos:
            aut = e.autorizacao_set.filter(ativo=True, aluno=self)
            if not aut:
                if e.unidade == self.unidade:
                    eventos_aluno.append(e)
                if e.aluno == self:
                    eventos_aluno.append(e)
                if e.turma == self.turma_atual:
                    eventos_aluno.append(e)
                if e.ciclo == self.turma_atual.get_ciclo:
                    eventos_aluno.append(e)
                if e.curso == self.turma_atual.get_curso:
                    eventos_aluno.append(e)
        eventos_aluno = list(dict.fromkeys(eventos_aluno))
        if eventos_aluno:
            for e in eventos_aluno:
                e.gera_aut_aluno(self)
        print('gestão de autorizações concluída!')

    def create_enturmacao(self, turma):
        enturmacao = Enturmacao(unidade=self.unidade,
                                aluno=self,
                                turma=turma)
        enturmacao.save()

    def remove_enturmacao(self):
        ent = self.enturmacao_set.get(ativo=True)
        ent.soft_delete()

    @property
    def turma_atual(self):
        tur = self.enturmacao_set.get(ativo=True).turma
        return tur

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'


class Enturmacao(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    unidade = models.ForeignKey(Unidade, verbose_name='Unidade', on_delete=models.PROTECT, blank=False, null=False)
    aluno = models.ForeignKey(Aluno, verbose_name='Aluno', on_delete=models.PROTECT, blank=False, null=False)
    turma = models.ForeignKey(Turma, verbose_name='Turma', on_delete=models.PROTECT, blank=False, null=False)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    def __str__(self):
        return self.aluno.nome + ' ' + self.turma.nome + ' - ' + str(self.turma.ano)

    @property
    def is_past_due(self):
        return timezone.now().year > self.turma.ano

    class Meta:
        verbose_name = 'Enturmação'
        verbose_name_plural = 'Enturmações'


class Evento(Base):
    GERADOR_CHOICES = [
        (1, 'Instituição'),
        (2, 'Família'),
        (3, 'JUND'),
    ]

    id = models.AutoField(primary_key=True, blank=False, null=False)
    nome = models.CharField("Nome", max_length=200, blank=False, null=False)
    descricao = models.CharField("Descricao", max_length=1000, blank=False, null=False)
    data_evento = models.DateField('Data', blank=False, null=False)
    gerador = models.IntegerField("Gerador", choices=GERADOR_CHOICES, blank=False, null=False, default=1)
    data_termino = models.DateField('Data Término', blank=True, null=True)
    data_cancelamento = models.DateField('Data Cancelamento', blank=True, null=True)
    local_evento = models.CharField("Cidade/UF", max_length=100, blank=False, null=False)
    aluno = models.ForeignKey(Aluno, verbose_name='Aluno', on_delete=models.SET_NULL, blank=True, null=True)
    turma = models.ForeignKey(Turma, verbose_name='Turma', on_delete=models.SET_NULL, blank=True, null=True)
    ciclo = models.ForeignKey(Ciclo, verbose_name='Ciclo', on_delete=models.SET_NULL, blank=True, null=True)
    curso = models.ForeignKey(Curso, verbose_name='Curso', on_delete=models.SET_NULL, blank=True, null=True)
    unidade = models.ForeignKey(Unidade, verbose_name='Unidade', on_delete=models.SET_NULL, blank=True, null=True)
    obs_cancelamento = models.CharField("Obs. Cancelamento", max_length=400, blank=True, null=True)
    msg_erro_cancelamento = models.CharField("Mens. Erro Cancelamento", max_length=400, blank=True, null=True)

    def gera_autorizacoes(self, tipo):
        alunos = []
        model = AutorizacoesModel.objects.get(pk=tipo)
        if self.aluno is not None:
            alunos.append(self.aluno)

        if self.turma is not None:
            ent = Enturmacao.objects.filter(turma=self.turma)
            for item in ent:
                alunos.append(item.aluno)

        if self.ciclo is not None:
            ciclo = Ciclo.objects.get(pk=self.ciclo.pk)
            for item in ciclo.turma_set.all():
                for ent in item.enturmacao_set.all():
                    alunos.append(ent.aluno)

        if self.curso is not None:
            curso = Curso.objects.get(pk=self.curso.pk)
            for ciclo in curso.ciclo_set.all():
                for turma in ciclo.turma_set.all():
                    for ent in turma.enturmacao_set.all():
                        alunos.append(ent.aluno)

        if self.unidade is not None:
            unidade = Unidade.objects.get(pk=self.unidade.pk)
            for curso in unidade.curso_set.all():
                for ciclo in curso.ciclo_set.all():
                    for turma in ciclo.turma_set.all():
                        for ent in turma.enturmacao_set.all():
                            alunos.append(ent.aluno)

        autorizacoes_geradas = self.autorizacao_set.filter(tipo=model)
        alunos_processados = []
        for a in autorizacoes_geradas:
            alunos_processados.append(a.aluno)
        lista_nova = set(alunos_processados) ^ set(alunos)
        if len(lista_nova) > 0:
            for aluno in lista_nova:
                aut = Autorizacao(evento=self,
                                  responsavel=aluno.responsavel,
                                  tipo=model,
                                  aluno=aluno,
                                  termos=model.texto)
                aut.save()
                send_new_notification_mail(self, aluno.responsavel)

    def gera_aut_aluno(self, aluno):
        tipo_aut = self.eventotipoautorizacao_set.filter(ativo=True)
        for tipo in tipo_aut:
            aut = Autorizacao(evento=self,
                              responsavel=aluno.responsavel,
                              tipo=tipo.tipo_autorizacao,

apps/autorizacoes/forms.py
from django import forms
from .models import (
    Evento,
    AutorizacoesModel,
    Autorizacao,
    AnexoAutorizacao
)


class EventoForm(forms.ModelForm):
    tipo_autorizacao = forms.ModelMultipleChoiceField(queryset=AutorizacoesModel.objects.all(),
                                                      widget=forms.SelectMultiple)

    class Meta:
        model = Evento
        fields = '__all__'

    # this function will be used for the validation
    def clean(self):

        # data from the form is fetched using super function
        super(EventoForm, self).clean()
        count = 0
        check = [self.cleaned_data.get('aluno'),
                 self.cleaned_data.get('turma'),
                 self.cleaned_data.get('ciclo'),
                 self.cleaned_data.get('curso'),
                 self.cleaned_data.get('unidade')]
        nome = self.cleaned_data.get('nome')
        for item in check:
            if item is None:
                count += 1

        if count == 5:
            self._errors['aluno'] = self.error_class([
                'Defina o escopo para o evento!'])

        if count < 4:
            self._errors['aluno'] = self.error_class([
                'Escolha apenas UM escopo para o evento!'])

        # return any errors if found
        return self.cleaned_data


class EventoEditForm(forms.ModelForm):
    tipo_autorizacao = forms.ModelMultipleChoiceField(queryset=AutorizacoesModel.objects.all(),
                                                      widget=forms.SelectMultiple,
                                                      required=False)

    class Meta:
        model = Evento
        fields = ['nome', 'data_evento', 'data_termino', 'local_evento', 'descricao']


class EventoCancelForm(forms.ModelForm):

    class Meta:
        model = Evento
        fields = ['obs_cancelamento']


class AutorizacaoForm(forms.ModelForm):
    tipo = forms.CharField(label='Tipo')
    data_evento = forms.DateField(label='Data início')
    data_termino = forms.DateField(label='Data fim')
    descricao = forms.CharField(label='Descrição')

    class Meta:
        model = Autorizacao
        fields = ['aluno']


class AnexoAutorizacaoForm(forms.ModelForm):
    class Meta:
        model = AnexoAutorizacao
        fields = ['arquivo', 'descricao']

apps/autorizacoes/templates/autorizacoes/anexoautorizacao_form.html
{% extends 'autorizador_base.html' %}
{% block autorizador %}
<div class="heading-block fancy-title nobottomborder">
    <table class="table">
        <tr>
            <td width="90%"><h4>Novo anexo para</h4> - {{autorizacao}} - {{autorizacao.evento.data_evento}}</td>
            <td align="right"><a href="{% url 'index' %}" class="button button-border button-rounded button-red" disabled="disabled">Cancelar</a></td>
        </tr>
    </table>
</div>

<div class="container mw-md">
    <!-- Form Solicitação -->
    <div class="col-lg-12 pl-lg-5 just-text">
        <form class="row" id="form-anexo_solicitacao" method="post" action="#" enctype="multipart/form-data">
        {{ form.non_field_errors }}
        {% csrf_token %}
            <input type="hidden" name="autorizacao" value={{autorizacao.pk}} />
            <input type="hidden" name="numero" value={{numero_seq}} />
            <div class="form-process">
                <div class="css3-spinner">
                    <div class="css3-spinner-scaler"></div>
                </div>
            </div>
            <div class="col-12 bottommargin">
                <label>Selecione um arquivo para anexar</label><br>
                <input type="file" id="anexo_solicitacao-arquivo" name="arquivo" class="file-loading"
                       data-show-preview="false" required/>
            </div>
            <div class="col-12 form-group">
                <input type="text" name="descricao" id="anexo_solicitacao-descricao" class="form-control"
                placeholder="Descrição" required>
            </div>
           <div class="divider" style="margin: 1rem;"></div>
            <div class="col-12 d-none">
                <input type="text" id="anexo_solicitacao-botcheck" name="anexo_solicitacao-botcheck" value="" />
            </div>
            <div class="col-12">
                <button type="submit" name="anexo_solicitacao-submit" id="anexo_solicitacao-submit"
                        class="button button-border button-rounded button-blue">Enviar</button>
            </div>
            <input type="hidden" name="prefix" value="solicitacao-" />

        </form>
    </div>
    <div class="w-100 line d-block d-md-none"></div>
</div>

{% endblock %}

apps/autorizacoes/templates/autorizacoes/autorizacao_form.html
{% extends 'autorizador_base.html' %}
{% block autorizador %}
<div class="heading-block fancy-title nobottomborder">
    <table class="table">
        <tr>
            <td width="90%"><h4>Nova Solicitação</h4> - {{tipo.nome}}</td>
            <td align="right"><a href="{% url 'index' %}" class="button button-border button-rounded button-red" disabled="disabled">Cancelar</a></td>
        </tr>
    </table>
</div>

<div class="container mw-md">
    <!-- Form Solicitação -->
    <div class="col-lg-12 pl-lg-5 just-text">
        <form class="row" id="form-solicitacao" method="post" action="#" enctype="multipart/form-data">
        {{ form.non_field_errors }}
        {% csrf_token %}
            <input type="hidden" name="tipo" value={{tipo.pk}} />
            <div class="form-process">
                <div class="css3-spinner">
                    <div class="css3-spinner-scaler"></div>
                </div>
            </div>
            <div class="col-12 form-group">
                <select name="aluno" class="form-select" id="id_aluno" required>
                    <option value="" selected>-- Aluno --</option>
                    {% for item in dependentes %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-12 bottommargin-sm">
                <div class="input-daterange component-datepicker input-group">
                    <input type="text" name="data_evento" value="" class="form-control text-start" placeholder="Selecione a data">
                    <div class="input-group-text">à</div>
                    <input type="text" name="data_termino" value="" class="form-control text-start" placeholder="Selecione a data">
                </div>
            </div>
            <div class="col-12 form-group">
                <textarea name="descricao" id="solicitacao-descricao" class="form-control" cols="30" rows="5"
                          maxlength="1000" minlength="20"
                style="resize: none;" placeholder="Motivo da solicitação (mínimo de 20 caracteres)" onkeyup="countChar(this)" required></textarea>
                <div id="charNum">1000</div>
            </div>
           <div class="divider" style="margin: 1rem;"></div>
            <div class="col-12 d-none">
                <input type="text" id="solicitacao-botcheck" name="solicitacao-botcheck" value="" />
            </div>
            <div class="col-12">
                <button type="submit" name="solicitacao-submit" id="solicitacao-submit" class="button button-border button-rounded button-blue">Enviar</button>
            </div>
            <input type="hidden" name="prefix" value="solicitacao-" />

        </form>
    </div>
    <div class="w-100 line d-block d-md-none"></div>
</div>

{% endblock %}

apps/autorizacoes/templates/autorizacoes/evento_edit_form.html
{% extends 'coordenador_base.html' %}
{% block coord %}
<div class="heading-block fancy-title nobottomborder">
    <table class="table">
        <tr>
            <td width="90%"><h4>Alterar Evento {{object.nome}}</h4></td>
            <td align="right"><a href="{% url 'index' %}" class="button button-border button-rounded button-red" disabled="disabled">Cancelar</a></td>
        </tr>
    </table>
</div>

<div class="container mw-md">
    <!-- Form Evento -->
    <div class="col-lg-12 pl-lg-5 just-text">
        <h3>Alterar evento</h3>

        <form class="row" id="form-eventos" method="post" action="#" enctype="multipart/form-data">
            {{ form.non_field_errors }}
            {% csrf_token %}
            <div class="form-process">
                <div class="css3-spinner">
                    <div class="css3-spinner-scaler"></div>
                </div>
            </div>

            <div class="col-6 form-group">
                <input type="text" name="nome" id="eventos-nome" class="form-control" value="{{ object.nome }}" required>
            </div>

            <div class="col-md-6 bottommargin-sm">
                <div class="input-daterange component-datepicker input-group">
                    <input type="text" name="data_evento" value="{{ object.data_evento|date:'d/m/Y' }}" class="form-control text-start" placeholder="">
                    <div class="input-group-text">à</div>
                    <input type="text" name="data_termino" value="{{ object.data_termino|date:'d/m/Y' }}" class="form-control text-start" placeholder="">
                </div>
            </div>

            <div class="col-12 form-group">
                <input type="text" name="local_evento" id="eventos-local" class="form-control"
                       value="{{object.local_evento}}"
                       required>
            </div>

            <div class="col-12 form-group">
                <textarea name="descricao" id="eventos-descricao" class="form-control" cols="30" rows="5"
                          maxlength="1000" minlength="20"
                style="resize: none;" onkeyup="countChar(this)" required>{{ object.descricao }}</textarea>
                <div id="charNum">1000</div>
            </div>

            {% if t_autorizacoes %}
            <div class="divider divider-lite">Autorizações Incluídas</div>
            <div class="table-responsive">
                <table class="table">
                    <tbody>
                        {% for e in t_autorizacoes %}
                        <tr>
                            <th>{{e.tipo_autorizacao.nome}}</th>
                            {% if not autorizacoes %}
                            <td>
                                <a href="{% url 'evento-ta-delete' e.pk %}">
                                    <i class="icon-trash"></i>
                                </a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}

            {% if autorizacoes_disponiveis %}
            <div class="divider divider-lite">Autorizações Disponíveis</div>
            <div class="col-12 form-group">
                <select class="selectpicker" name="tipo_autorizacao" id="id_tipo_autorizacao" multiple>
                    {% for item in autorizacoes_disponiveis %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            {% else %}
            <div class="divider divider-lite">Não há Autorizações Disponíveis</div>
            {% endif %}
            </div>

            <div class="divider" style="margin: 1rem;"></div>

            <div class="col-12 d-none">
                <input type="text" id="eventos-botcheck" name="eventos-botcheck" value="" />
            </div>
            <div class="col-12">
                <button type="submit" name="eventos-submit" id="eventos-submit" class="button button-border button-rounded button-blue">Salvar</button>
                <a href="#" class="button button-border button-rounded button-red" style="float: right;"
                       data-bs-toggle="modal" data-bs-target="#modal_delete_evento">Excluir</a>
            </div>

            <input type="hidden" name="prefix" value="jobs-" />
        </form>
    </div>

    {% include 'evento_deletion_modal.html' %}

</div>

{% endblock %}

apps/autorizacoes/templates/autorizacoes/evento_form.html
{% extends 'coordenador_base.html' %}
{% block coord %}
<div class="heading-block fancy-title nobottomborder">
    <table class="table">
        <tr>
            <td width="90%"><h4>Novo Evento</h4></td>
            <td align="right"><a href="{% url 'index' %}" class="button button-border button-rounded button-red" disabled="disabled">Cancelar</a></td>
        </tr>
    </table>
</div>

<div class="container mw-md">
    <!-- Form Evento -->
    <div class="col-lg-12 pl-lg-5 just-text">
        <form class="row" id="form-eventos" method="post" action="#" enctype="multipart/form-data">
        {{ form.non_field_errors }}
        {% csrf_token %}
            <div class="form-process">
                <div class="css3-spinner">
                    <div class="css3-spinner-scaler"></div>
                </div>
            </div>
            <input type="hidden" name="gerador" value=1 />
            <div class="col-6 form-group">
                <input type="text" name="nome" id="eventos-nome" class="form-control" value="" placeholder="Nome do Evento" required>
            </div>
<!--            <div class="col-md-6 bottommargin-sm">-->
<!--                <div class="input-daterange component-datepicker input-group">-->
<!--                    <input type="text" name="data_evento" value="" class="form-control text-start" placeholder="Selecione a data">-->
<!--                    <div class="input-group-text">à</div>-->
<!--                    <input type="text" name="data_termino" value="" class="form-control text-start" placeholder="Selecione a data">-->
<!--                </div>-->
<!--            </div>-->
            <div class="col-md-6 bottommargin-sm">
                <input type="text" value="" class="form-control text-start component-datepicker default"
                       name="data_evento" placeholder="Selecione a data">
            </div>
            <div class="col-12 form-group">
                <input type="text" name="local_evento" id="eventos-local" class="form-control"
                       value="{{coordenador.unidade}} - {{coordenador.unidade.cidade}}/{{coordenador.unidade.estado}}"
                       required>
            </div>
            <div class="col-12 form-group">
                <textarea name="descricao" id="eventos-descricao" class="form-control" cols="30" rows="5"
                          maxlength="1000" minlength="20"
                style="resize: none;" placeholder="Descrição (mínimo de 20 caracteres)" onkeyup="countChar(this)" required></textarea>
                <div id="charNum">1000</div>
            </div>

            <div class="divider divider-lite">Escopo do evento</div>
            {% if form.errors %}
            <div class="alert alert-danger" style="padding-bottom:0;"></i>{{ form.aluno.errors }}</div>
            {% endif %}

            <div class="col-6 form-group">
                <select name="aluno" class="form-select" id="id_aluno">
                    <option value="" selected>-- Aluno --</option>
                    {% for item in alunos %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-6 form-group">
                <select name="turma" class="form-select" id="id_turma">
                    <option value="" selected>-- Turma --</option>
                    {% for item in turmas %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-6 form-group">
                <select name="ciclo" class="form-select" id="id_ciclo">
                    <option value="" selected>-- Ciclo --</option>
                    {% for item in ciclos %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-6 form-group">
                <select name="curso" class="form-select" id="id_curso">
                    <option value="" selected>-- Curso --</option>
                    {% for item in cursos %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-6 form-group">
                <select name="unidade" class="form-select" id="id_unidade">
                    <option value="" selected>-- Unidade --</option>
                    {% for item in unidades %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="divider divider-lite">Autorizações Necessárias</div>
            <div class="col-12 form-group">
                <select style="border-color: red;" class="selectpicker" name="tipo_autorizacao" required id="id_tipo_autorizacao" multiple>
                    {% for item in t_autorizacoes %}
                    <option value="{{item.pk}}">{{item}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="divider" style="margin: 1rem;"></div>
            <div class="col-12 d-none">
                <input type="text" id="eventos-botcheck" name="eventos-botcheck" value="" />
            </div>
            <div class="col-12">
                <button type="submit" name="eventos-submit" id="eventos-submit" class="button button-border button-rounded button-blue">Salvar</button>
            </div>
            <input type="hidden" name="prefix" value="eventos-" />

        </form>
    </div>
    <div class="w-100 line d-block d-md-none"></div>
</div>

{% endblock %}

apps/autorizacoes/templates/autorizacoes/eventotipoautorizacao_confirm_delete.html
{% extends 'coordenador_base.html' %}
{% block coord %}
<div class="heading-block fancy-title nobottomborder">
    <table class="table">
        <tr>
            <td width="90%"><h4>Tem certeza que deseja excluir?</h4></td>
            <td align="right"><a href="#" onclick="history.back();" class="button button-border button-rounded button-red" disabled="disabled">Cancelar</a></td>
        </tr>
    </table>
</div>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" name="eventos-submit" id="eventos-submit" class="button button-border button-rounded button-red">Confirmar</button>
</form>
{% endblock %}