apps/privacidade/urls.py
from django.urls import path
from .views import PrivacidadeFormView

urlpatterns = [
    path('', PrivacidadeFormView.as_view(), name='privacidade'),
]

nd_box/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', include('apps.core.urls')),
    path('manager/', admin.site.urls),
    path('carreiras/', include('apps.carreiras.urls')),
    path('reports/', include('apps.reports.urls')),
    path('privacidade/', include('apps.privacidade.urls')),
    path('autorizacoes/', include('apps.autorizacoes.urls')),
    path('healt/', include('apps.healt.urls')),
    path('jund/', include('apps.jund.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Gestão ND Box'
admin.site.site_title = 'Gestão ND Box'
admin.site.index_title = 'Área Administrativa'

apps/privacidade/models.py
from django.db import models

# Create your models here.

apps/privacidade/forms.py
from django import forms
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string


class ContactForm(forms.Form):
    SUBJECT = [
        (None, '-- Finalidade do contato --'),
        ('1', 'Acessar meus dados pessoais'),
        ('2', 'Receber meus dados pessoais em formato simplificado'),
        ('3', 'Retificar meus dados pessoais'),
        ('4', 'Solicitar a exclusão dos meus dados pessoais'),
        ('5', 'Confirmar a existência de tratamento dos meus dados pessoais'),
        ('6', 'Outros'),
    ]
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail', max_length=100)
    subject = forms.ChoiceField(label='Assunto', choices=SUBJECT)
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        subject = self.cleaned_data['subject']
        subject = dict(self.fields['subject'].choices)[subject]
        email_template_name = 'email/privacy_request.html'
        m_context = {
            "name": self.cleaned_data['name'],
            "email": self.cleaned_data['email'],
            "message": self.cleaned_data['message'],
            "sender": 'Privacidade'
        }
        email = render_to_string(email_template_name, m_context)
        subject = subject
        from_email = '"Sistema ND Box | Privacidade" <contato@nd.org.br>'
        to = 'dpo@nd.org.br'
        msg = EmailMultiAlternatives(subject, email, from_email, [to])
        msg.attach_alternative(email, "text/html")

        msg.send()

apps/privacidade/views.py
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import ContactForm


class PrivacidadeFormView(FormView):
    template_name = 'privacidade.html'
    form_class = ContactForm
    success_url = reverse_lazy('privacidade')

    def get_context_data(self, **kwargs):
        context = super(PrivacidadeFormView, self).get_context_data(**kwargs)
        context['doc_title'] = 'Privacidade'
        context['top_app_name'] = 'Privacidade'
        context['pt_h1'] = 'Política de Privacidade e Proteção de Dados'
        context['pt_span'] = 'Nós levamos a sério a sua privacidade'
        context['pt_breadcrumb2'] = 'Privacidade'
        return context

    def form_valid(self, form, *args, **kwargs):
        form.send_mail()
        messages.success(self.request, 'E-mail enviado com sucesso')
        return super(PrivacidadeFormView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Erro ao enviar e-mail')
        return super(PrivacidadeFormView, self).form_invalid(form, *args, **kwargs)

apps/privacidade/templates/mail_form.html
<form class="row" id="mail-form" action="#" method="POST">
{% csrf_token %}
    <div class="form-process">
        <div class="css3-spinner">
            <div class="css3-spinner-scaler"></div>
        </div>
    </div>
    <div class="col-6 form-group">
        <input type="text" name="name" maxlength="100" class="form-control" placeholder="Nome" required id="id_name">
    </div>
    <div class="col-6 form-group">
        <input type="email" name="email" maxlength="100" class="form-control" placeholder="E-mail" required id="id_email">
    </div>
    <div class="col-12 form-group">
        <select name="subject" class="form-select required" required id="id_subject">
            <option value="" selected>-- Finalidade do contato --</option>
            <option value="1">Acessar meus dados pessoais</option>
            <option value="2">Receber meus dados pessoais em formato simplificado</option>
            <option value="3">Retificar meus dados pessoais</option>
            <option value="4">Solicitar a exclusão dos meus dados pessoais</option>
            <option value="5">Confirmar a existência de tratamento dos meus dados pessoais</option>
            <option value="6">Outros</option>
        </select>
    </div>
    <div class="col-12 form-group">
        <textarea name="message" class="form-control" cols="40" rows="10" required id="id_message" style="resize: none;"
                  maxlength="200" placeholder="Sua mensagem"></textarea>
    </div>
    <div class="col-12">
        <button type="submit" name="lgpd-submit" id="lgpd-submit" class="button button-border button-rounded button-blue">Enviar</button>
    </div>
    <input type="hidden" name="prefix" value="lgpd-">
</form>

apps/privacidade/templates/privacidade.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'visao_geral.html' %}

{% endblock %}