apps/carreiras/urls.py
from django.urls import path
from .views import (
    CarreirasFormView,
    VagaCreate,
    VagaView,
    VagaEdit,
    VagaDelete,
    VagaList,
    VagaFechar,
    CandidaturaList,
    CandidaturaView,
    CandidaturaVagaList,
)

urlpatterns = [
    path('lista_aplicacoes', CandidaturaList.as_view(), name='aplicacoes-list'),
    path('', CarreirasFormView.as_view(), name='carreiras'),
    path('vaga/create/', VagaCreate.as_view(), name='vaga-create'),
    path('vaga/<int:pk>/', VagaView.as_view(), name='vaga-detail'),
    path('vaga/update/<int:pk>/', VagaEdit.as_view(), name='vaga-update'),
    path('vaga/delete/<int:pk>/', VagaDelete.as_view(), name='vaga-delete'),
    path('vaga/list/', VagaList.as_view(), name='vaga-list'),
    path('vaga/fechar/<int:pk>/', VagaFechar.as_view(), name='vaga-fechar'),
    path('candidatura/<int:pk>/', CandidaturaView.as_view(), name='candidatura-detail'),
    path('candidatura/vaga/<int:pk>/', CandidaturaVagaList.as_view(), name='candidatura-vaga')
]

nd_box/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', include('apps.core.urls')),
    path('manager/', admin.site.urls),
    path('carreiras/', include('apps.carreiras.urls')),
    path('reports/', include('apps.reports.urls')),
    path('privacidade/', include('apps.privacidade.urls')),
    path('autorizacoes/', include('apps.autorizacoes.urls')),
    path('healt/', include('apps.healt.urls')),
    path('jund/', include('apps.jund.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Gestão ND Box'
admin.site.site_title = 'Gestão ND Box'
admin.site.index_title = 'Área Administrativa'

apps/carreiras/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from apps.core.models import Unidade, Base
from functions import get_file_path
from datetime import date, timedelta


class Area(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    nome = models.CharField('Nome', max_length=200, blank=False, null=False)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Área de Interesse'
        verbose_name_plural = 'Áreas de Interesse'


class Escolaridade(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    nome = models.CharField('Nome', max_length=200, blank=False, null=False)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Escolaridade'
        verbose_name_plural = 'Escolaridades'


class Vaga(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    unidade = models.ForeignKey(Unidade, verbose_name='Unidade', on_delete=models.SET_NULL, blank=True, null=True)
    cod_vaga = models.CharField('Código', max_length=200, blank=True, null=True)
    area_interesse = models.ForeignKey(Area, verbose_name='Área de interesse', on_delete=models.SET_NULL, blank=True,
                                       null=True)
    titulo = models.CharField('Título', max_length=200, blank=False, null=False)
    descricao = models.TextField('Descrição', max_length=1000, blank=False, null=False)
    escolaridade = models.ForeignKey(Escolaridade, verbose_name='Escolaridade', on_delete=models.SET_NULL, blank=True,
                                     null=True)
    tempo_experiencia = models.CharField('Tempo de experiência', max_length=200, blank=True, null=True)
    aberta = models.BooleanField('Aberta', default=True)
    preenchida = models.BooleanField('Preenchida', default=False)
    msg_erro_exclusao = models.CharField("Mens. Erro exclusão", max_length=400, blank=True, null=True)
    data_fechamento = models.DateField('Data Fechamento', blank=True, null=True)
    data_preenchida = models.DateField('Data Preenchimento', blank=True, null=True)

    @staticmethod
    def get_absolute_url():
        return reverse('index')

    @property
    def nbr_applications(self):
        return len(self.candidatura_set.all())

    def soft_delete(self):
        candidaturas = self.candidatura_set.all()
        if candidaturas:
            self.msg_erro_exclusao = 'Não é possível excluir esta vaga, pois existem candidaturas' \
                                     ' ativas. Ao invés ' \
                                     'disso, tente fechar'
            self.save()
            return False
        else:
            self.ativo = False
            self.data_desativado = timezone.now()
            self.save()
            return True

    def close(self):
        self.data_fechamento = timezone.now()
        self.aberta = False
        self.save()

    def fill(self):
        self.data_preenchida = timezone.now()
        self.preenchida = True
        self.close()

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Vaga'
        verbose_name_plural = 'Vagas'


class Candidatura(Base):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    cod_vaga = models.ForeignKey(Vaga, verbose_name='Vaga', on_delete=models.SET_NULL, blank=True, null=True)
    nome = models.CharField('Nome', max_length=200, blank=False, null=False)
    email = models.CharField('E-mail', max_length=200, blank=False, null=False)
    cidade = models.CharField('Cidade', max_length=200, blank=True, null=True, default='Canoas')
    telefone = models.CharField('Telefone', max_length=15, blank=False, null=False)
    escolaridade = models.ForeignKey(Escolaridade, verbose_name='Escolaridade', on_delete=models.SET_NULL, blank=True,
                                     null=True)
    curso = models.CharField('Curso', max_length=100, blank=True, null=True)
    historico = models.TextField('Pós-graduação', max_length=300, blank=True, null=True)
    area_interesse = models.ForeignKey(Area, on_delete=models.SET_NULL, verbose_name='Área de interesse', blank=True,
                                       null=True, default=None)
    unidade_interesse = models.ForeignKey(Unidade, on_delete=models.SET_NULL, verbose_name='Unidade de interesse',
                                          blank=True, null=True, default=None)
    tempo_experiencia = models.CharField('', max_length=100, blank=True, null=True)
    arquivo = models.FileField(upload_to=get_file_path)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def soft_delete(self):
        self.ativo = False
        self.data_desativado = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cod_vaga) + ' - ' + str(self.nome)

    @property
    def expire_date(self):
        return self.data_criacao + timedelta(days=365)

    @property
    def is_past_due(self):
        return date.today() > self.data_criacao

    class Meta:
        verbose_name = 'Candidatura'
        verbose_name_plural = 'Candidaturas'

apps/carreiras/views.py
from django.http import HttpResponseRedirect
from django.views.generic import (
    FormView,
    ListView,
    DetailView,
    DeleteView,
)
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from .models import (
    Candidatura,
    Vaga,
    Escolaridade,
    Unidade,
    Area
)
from .forms import (
    CandidaturaForm,
    VagaForm,
    VagaEditForm,
    VagaSearchForm
)
from django.views.generic import (
    CreateView,
    UpdateView,
    View
)


class CarreirasFormView(FormView):
    template_name = 'carreiras_aplicar.html'
    form_class = CandidaturaForm
    success_url = reverse_lazy('carreiras')

    def get_context_data(self, **kwargs):
        vagas = Vaga.objects.filter(ativo=True, aberta=True)
        niveis = Escolaridade.objects.all()
        areas = Area.objects.all()
        unidades = Unidade.objects.all()
        cidades = []
        for item in unidades:
            cidades.append(item.cidade)

        cidades = list(dict.fromkeys(cidades))

        context = super(CarreirasFormView, self).get_context_data(**kwargs)
        context['doc_title'] = 'Trabalhe conosco'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'faça parte do nosso time!'
        context['pt_span'] = 'Cadastre-se e envie seu currículo'
        context['pt_breadcrumb2'] = 'Trabalhe conosco'
        context['vagas'] = vagas
        context['niveis'] = niveis
        context['areas'] = areas
        context['unidades'] = unidades
        context['cidades'] = cidades
        return context

    def form_valid(self, form, *args, **kwargs):
        apply = form.save(commit=False)
        if apply.cod_vaga:
            apply.cidade = apply.cod_vaga.unidade.cidade
            apply.area_interesse = apply.cod_vaga.area_interesse
            apply.unidade_interesse = apply.cod_vaga.unidade

        apply.ativo = True
        apply.consentimento_1 = True
        apply.consentimento_2 = True
        apply.consentimento_3 = True
        apply.save()
        form.send_mail(apply)
        messages.success(self.request, 'E-mail enviado com sucesso')
        return super(CarreirasFormView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Erro ao enviar e-mail')
        print(form.errors)
        return super(CarreirasFormView, self).form_invalid(form, *args, **kwargs)


class CarreirasList(ListView):
    model = Candidatura

    def get_context_data(self, **kwargs):
        context = super(CarreirasList, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        return context

    def get_queryset(self):
        return Candidatura.objects.all()


class VagaCreate(CreateView):
    model = Vaga
    form_class = VagaForm

    def get_context_data(self, **kwargs):
        niveis = Escolaridade.objects.all()
        areas = Area.objects.all()
        unidades = Unidade.objects.all()

        context = super(VagaCreate, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        context['niveis'] = niveis
        context['areas'] = areas
        context['unidades'] = unidades
        return context

    def form_valid(self, form, *args, **kwargs):
        vaga = form.save(commit=False)
        vaga.save()
        ax = vaga.area_interesse.nome[0:2].upper()
        bx = str(vaga.pk).zfill(5)
        cx = ''.join([x[0] for x in vaga.unidade.nome.split()])
        vaga.cod_vaga = ax + bx + cx
        vaga.save()

        messages.success(self.request, 'Vaga cadastrada')
        return super(VagaCreate, self).form_valid(form)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Erro ao cadastrar a vaga')
        return super(VagaCreate, self).form_invalid(form, *args, **kwargs)


class VagaView(DetailView):
    model = Vaga

    def get_context_data(self, **kwargs):
        context = super(VagaView, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        return context


class VagaEdit(UpdateView):
    model = Vaga
    form_class = VagaEditForm
    template_name = 'carreiras/vaga_edit_form.html'

    def get_context_data(self, **kwargs):
        niveis = Escolaridade.objects.all()
        areas = Area.objects.all()
        unidades = Unidade.objects.all()

        context = super(VagaEdit, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        context['niveis'] = niveis
        context['areas'] = areas
        context['unidades'] = unidades
        return context

    def form_valid(self, form, *args, **kwargs):
        messages.success(self.request, 'Vaga alterada')
        return super(VagaEdit, self).form_valid(form)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Erro ao alterar a vaga')
        return super(VagaEdit, self).form_invalid(form, *args, **kwargs)


class VagaDelete(DeleteView):
    model = Vaga
    success_url = reverse_lazy('index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.soft_delete():
            messages.success(self.request, 'Vaga excluída com sucesso!')
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.warning(self.request, self.object.msg_erro_exclusao)
            url = reverse('vaga-detail', kwargs={'pk': self.object.pk})
            return HttpResponseRedirect(url)


class VagaList(ListView):
    model = Vaga

    def get_queryset(self):
        vaga = Vaga.objects.filter(ativo=True).order_by('-data_criacao')
        return vaga

    def get_context_data(self, **kwargs):
        context = super(VagaList, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        return context


class VagaFechar(View):
    def get(self, *args, **kwargs):
        vaga = Vaga.objects.get(pk=self.kwargs['pk'])
        vaga.close()
        messages.success(self.request, 'Vaga fechada')
        url = reverse('vaga-detail', kwargs={'pk': vaga.pk})
        return HttpResponseRedirect(url)


class CandidaturaList(ListView):
    model = Candidatura

    def get_queryset(self):
        cand = Candidatura.objects.filter(ativo=True).order_by('unidade_interesse', 'cod_vaga')
        return cand

    def get_context_data(self, **kwargs):
        context = super(CandidaturaList, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        return context


class CandidaturaVagaList(ListView):
    model = Candidatura
    template_name = 'vaga_list.html'

    def get_queryset(self):
        vaga = Vaga.objects.get(pk=self.kwargs['pk'])
        cand = Candidatura.objects.filter(ativo=True, cod_vaga=vaga)
        return cand

    def get_context_data(self, **kwargs):
        context = super(CandidaturaVagaList, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        return context


class CandidaturaView(DetailView):
    model = Candidatura

    def get_context_data(self, **kwargs):
        context = super(CandidaturaView, self).get_context_data(**kwargs)
        context['doc_title'] = 'Portal de Carreiras'
        context['top_app_name'] = 'Carreiras'
        context['pt_h1'] = 'Portal de carreiras'
        context['pt_span'] = ''
        context['pt_breadcrumb2'] = 'Carreiras'
        return context

apps/carreiras/templates/application_form.html
<form class="row" id="form" method="post" action="#" enctype="multipart/form-data">
  {% csrf_token %}
    <div class="form-process">
        <div class="css3-spinner">
            <div class="css3-spinner-scaler"></div>
        </div>
    </div>
    <div class="col-12 form-group">
        <select name="cod_vaga" class="form-select" id="id_cod_vaga">
            <option value="" selected>-- Vaga --</option>
            {% for item in vagas %}
                <option value="{{item.id}}">{{item.titulo}} - {{item.unidade}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-6 form-group">
        <input type="text" name="{{ form.nome.name }}" id="jobs-name" class="form-control" value="" placeholder="Nome Completo" required>
    </div>
    <div class="col-6 form-group">
        <input type="email" name="{{ form.email.name }}" id="jobs-mail" class="form-control" value="" placeholder="E-mail" required>
    </div>
    <div class="col-6 form-group">
        <select name="cidade" class="form-select" required id="id_cidade">
            <option value="" selected>-- Cidade --</option>
            {% for item in cidades %}
                <option value="{{item}}">{{item}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-6 form-group">
        <input type="text" name="{{ form.telefone.name }}" id="jobs-phone" class="form-control" value="" placeholder="Telefone" required>
    </div>
    <div class="col-6 form-group">
        <select name="escolaridade" class="form-select" required id="id_escolaridade">
            <option value="" selected>-- Escolaridade --</option>
            {% for item in niveis %}
                <option value="{{item.id}}">{{item.nome}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-6 form-group">
        <input type="text" name="{{ form.curso.name }}" id="jobs-course" class="form-control" value="" placeholder="Curso" disabled>
    </div>
    <div class="col-12 form-group">
        <textarea name="{{ form.historico.name }}" id="jobs-subject" class="form-control" cols="30" rows="5" maxlength="200"
        style="resize: none;" placeholder="Pós-graduação"></textarea>
    </div>
    <div class="col-6 form-group">
        <select name="area_interesse" class="form-select" required id="id_area_interesse">
            <option value="" selected>-- Área pretendida --</option>
            {% for item in areas %}
                <option value="{{item.id}}">{{item.nome}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-6 form-group">
        <select name="unidade_interesse" class="form-select" required id="id_unidade_interesse">
            <option value="" selected>-- Unidade de interesse --</option>
            {% for item in unidades %}
                <option value="{{item.id}}">{{item.nome}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-md-12 form-group">
        <div class="label">
            <label>Possui experiência na função?</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="sim">
            <label class="form-check-label" for="inlineRadio1">Sim</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="nao">
            <label class="form-check-label" for="inlineRadio2">Não</label>
        </div>
        <input type="text" name="{{ form.tempo_experiencia.name }}" id="jobs-ex-time" class="form-control" value="" placeholder="Tempo de experiência">
    </div>
    <div class="col-12 bottommargin">
        <label>Adicione seu currículo. ATENÇÃO! Apenas arquivos tipo PDF:</label><br>
        <input type="file" id="jobs-resume" name="{{ form.arquivo.name }}" class="file-loading"
        data-allowed-file-extensions='["pdf"]' data-show-preview="false" required/>
    </div>
    <label>Para submeter sua inscrição, leia com atenção e marque os itens abaixo</label>
    <div class="col-12 just-text">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="jobs-check1" name="{{ form.consentimento_1.name }}" required>
            <label class="form-check-label" for="jobs-check1">
                Estou ciente e dou consentimento livre à Associação Notre Dame para a utilização dos meus dados
                pessoais e dados sensíveis, bem como que as informações prestadas serão destinadas somente para
                minha participação em processos seletivos da instituição, conforme Lei Geral de Proteção de Dados
                – Lei nº 13.709/2018.
            </label>
        </div>
    </div>
    <div class="divider" style="margin: 1rem;"></div>
    <div class="col-12 just-text">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="jobs-check2" name="{{ form.consentimento_2.name }}" required>
            <label class="form-check-label" for="jobs-check2">
                Autorizo a Associação Notre Dame a acessar essas informações e direcionar a minha participação
                nos processos seletivos para preenchimento de vagas com as quais eu estiver de acordo com os requisitos
                exigidos pela instituição.
            </label>
        </div>
    </div>
    <div class="divider" style="margin: 1rem;"></div>
    <div class="col-12 just-text">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="jobs-check3" name="{{ form.consentimento_3.name }" required>
            <label class="form-check-label" for="jobs-check3">
                Estou ciente que os dados informados serão descartados pela instituição após seis meses da
                realização deste cadastro e caso seja de meu interesse, efetuarei nova inscrição para participar de processos seletivos.
            </label>
        </div>
    </div>
    <div class="divider" style="margin: 1rem;"></div>
    <div class="col-12 d-none">
        <input type="text" id="jobs-botcheck" name="jobs-botcheck" value="" />
    </div>
    <div class="col-12">
        <button type="submit" name="jobs-submit" id="jobs-submit" class="button button-border button-rounded button-blue">Enviar</button>
    </div>

    <input type="hidden" name="prefix" value="jobs-">

</form>
<script>
    document.getElementById("id_escolaridade").onchange =
    function() {
        var slctd = document.getElementById("id_escolaridade").value;
        if(slctd > 4) {
            document.getElementById("jobs-course").disabled = false;
        }
        else{
            ipt = document.getElementById("jobs-course");
            ipt.value = '';
            ipt.disabled = true;
        }
    }
</script>
<script>
    document.getElementById("id_cod_vaga").onchange =
    function() {
        var slctd = document.getElementById("id_cod_vaga").value;
        if(slctd != ""){
            document.getElementById("id_cidade").disabled = true;
            document.getElementById("id_cidade").required = false;

            document.getElementById("id_area_interesse").disabled = true;
            document.getElementById("id_area_interesse").required = false;

            document.getElementById("id_unidade_interesse").disabled = true;
            document.getElementById("id_unidade_interesse").required = false;
        }
        else{
            document.getElementById("id_cidade").disabled = false;
            document.getElementById("id_cidade").required = true;

            document.getElementById("id_area_interesse").disabled = false;
            document.getElementById("id_area_interesse").required = true;

            document.getElementById("id_unidade_interesse").disabled = false;
            document.getElementById("id_unidade_interesse").required = true;
        }
    }
</script>

apps/carreiras/templates/carreiras_aplicar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Content
============================================= -->
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <div class="row">
                <div class="col-lg-6 pl-lg-5 just-text">
                    <blockquote class="bottommargin blockquote-reverse">
                        <p>Para atendermos alunos, pais e comunidade de forma transformadora, sólida e com valores, buscamos profissionais que assumam conosco a responsabilidade,
                            o empenho e a coragem de dar continuidade à nobre missão de educar com bondade, firmeza e competência.
                        </p>
                        <p>
                            Faça parte desta construção de propósito!
                        </p>
                    </blockquote>
                </div>
                <div class="col-lg-6 bottommargin">

                    {% include 'application_form.html' %}

                </div>
            </div>


        </div>
    </div>
</section><!-- #content end -->


{% endblock %}

apps/carreiras/templates/carreiras_base.html
{% extends 'base.html' %}

{% block content %}
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <div class="row">
                {% block carreiras %} {% endblock %}
            </div>
        </div>
    </div>
</section>


{% endblock %}

apps/carreiras/templates/carreiras_index.html
{% load static %}
<!-- Content
============================================= -->
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">

            <div class="row">
                <div class="postcontent col-lg-9">

                    <a href="{% url 'vaga-create' %}" class="button button-border button-rounded button-blue" disabled="disabled" style="float: right;">Nova vaga</a>

                    <h2>Últimas Vagas Abertas</h2>
                    <div class="row">

                        {% for vaga in vagas %}
                        <div class="entry event col-12" style="margin-bottom:10px">
                            <div class="grid-inner row align-items-center g-0 p-4">
                                <div class="col-md-8 ps-md-4">
                                    <div class="entry-title title-xs">
                                        <h2><a href="{% url 'vaga-detail' vaga.pk %}">{{ vaga.titulo }} - {{ vaga.cod_vaga }}</a></h2>
                                    </div>
                                    <div class="entry-meta">
                                        <ul>
                                            <li><i class="icon-line-tool"></i> {{ vaga.area_interesse }}</li>
                                            <li><i class="icon-map-marker2"></i> {{ vaga.unidade }}</li>
                                            <li><i class="icon-line2-puzzle"></i> {{ vaga.nbr_applications }}</li>
                                        </ul>
                                    </div>

                                </div>
                            </div>
                        </div>
                        {% empty %}

                        <div class="entry event col-12">
                            <div class="grid-inner row g-0 p-4">
                                <div class="col-md-5 mb-md-0">
                                    <h3>Sem vagas abertas</h3>
                                </div>
                            </div>
                        </div>

                        {% endfor %}

                    </div>

                </div>

                <div class="w-100 line d-block d-md-none"></div>
                <div class="col-md-3">
                    <div class="list-group">
                        <a href="{% url 'vaga-list' %}" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Vagas</div><i class="icon-handshake"></i></a>
                        <a href="{% url 'aplicacoes-list' %}" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Candidaturas</div><i class="icon-child"></i></a>
                        <a href="#" data-bs-toggle="modal" data-bs-target="#modal_new_feature"
                           class="list-group-item list-group-item-action d-flex justify-content-between" title="Em breve!">
                            <div>Mensagens</div><i class="icon-envelope1"></i>
                        </a>
                        <a href="{% url 'logout' %}" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Logout</div><i class="icon-sign-out-alt"></i></a>
                    </div>
                    <div class="fancy-title topmargin title-border">
                        <h4>Reflexão</h4>
                    </div>
                    <blockquote class="quote" style="color: black;">
                        <p><i>{{ quote }}</i></p>
                        <footer class="blockquote-footer">{{ author }}</footer>
                    </blockquote>
                </div>
            </div>
        </div>
        {% include 'new_feature_modal.html' %}
    </div>
</section><!-- #content end -->

apps/carreiras/templates/vaga_deletion_modal.html
<!-- Modal -->
<div class="modal fade" id="modal_delete_vaga" tabindex="-1" role="dialog" aria-labelledby="modal_delete_vaga_label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Confirmar exclusão</h4>
                <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-hidden="true"></button>
            </div>

            <div class="modal-body">

                <h3>Tem certeza que deseja excluir esta vaga?</h3>
                <div class="entry-content">
                    <form method="POST" action="{% url 'vaga-delete' object.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">Excluir</button>
                    </form>
                </div>

            </div>

        </div>
    </div>
</div>